# Site settings
title: Юрий Матюхин
email: ymatuhin@yandex.ru
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ymatuhin.ru" # the base hostname & protocol for your site
twitter_username: ymatuhin
github_username: ymatuhin
permalink: /:categories/:title
sass:
  style: compressed
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []

# Build settings
markdown: kramdown
