# Site settings
title: Юрий Матюхин
email: ymatuhin@yandex.ru
baseurl: ""
url: "http://ymatuhin.ru"

twitter: 		ymatuhin
github:         ymatuhin
email: 			ymatuhin@yandex.ru
disqus: 		ymatuhin

permalink: /:categories/:title
paginate: 5
paginate_path: "page:num"

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

sass:
  style: compressed

excerpt_separator: <!-- more -->

# Build Settings
permalinks: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
