# Site settings
title: Юрий Матюхин
email: ymatuhin@yandex.ru
baseurl: ""
url: "http://ymatuhin.ru"

twitter: 		ymatuhin
github:         ymatuhin
email: 			ymatuhin@yandex.ru
disqus: 		ymatuhin
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-last-modified-at

permalink: /:categories/:title
destination: ../_site
sass:
  style: compressed

excerpt_separator: <!-- more -->

# Build Settings
permalinks: pretty
markdown: redcarpet
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

jekyll_timeago:
  depth: 1
  today: 'сегодня'
  yesterday: 'вчера'
  tomorrow: 'завтра'
  and: 'и'
  suffix: 'назад'
  prefix: ''
  suffix_future: ''
  prefix_future: 'в'
  years: 'лет'
  year: 'год'
  months: 'месяца'
  month: 'месяц'
  weeks: 'недель'
  week: 'неделя'
  days: 'дней'
  day: 'день'
